# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.PositiveSmallIntegerField(auto_created=True)),
                ('projectname', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=200)),
                ('lastmodified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('schoolname', models.CharField(max_length=100)),
                ('schooladdress', models.CharField(max_length=200)),
                ('subjects', models.CharField(max_length=200)),
            ],
        ),
    ]
